Adding popup window
edahigure/Portfolio-setup-and-mobile-first pull request #13
Opened 2022-10-21 21:26 UTC by edahigure

In this branch, we have implemented a pop-up window showing information about the projects when the user clicks the buttons.

2022-10-21 22:34 UTC, jerryowusu requested changes
Hi @edahigure 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few issues to need to work on and make your project look professional :sunglasses:

![soclose](https://user-images.githubusercontent.com/65233860/197297835-7c4e27a0-9810-4610-85a4-19e6b758a96d.gif)


## Highlights
:heavy_check_mark: All linters are passing
:heavy_check_mark: Good commit messages
:heavy_check_mark: Follow correct GitHub flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] Kindly follow the readme [template](https://github.com/microverseinc/readme-template/blob/master/README.md), ensure that all sections and headers are available to make your project look more proffessional and up to standard

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 22:34 UTC, jerryowusu commented on project.js
> +                   <p class="works-description-popup">
Kindly ensure that the popup follows the design for both the desktop and mobile versions from the chosen template in figma. :+1: 

- [ ] Kindly fix the width and height of the pop-up for both versions of mobile and desktop. It should also be in the center and responsive.
- [ ] Check the position of the `languages`, the project image and the `see source button` etc.



Your mobile pop-up            |  The figma template
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-21 22-15-00](https://user-images.githubusercontent.com/65233860/197297158-a4511da8-ad6b-43e8-a440-ec910e174b17.png)  |  ![Screenshot from 2022-10-21 22-16-46](https://user-images.githubusercontent.com/65233860/197297183-5903c063-d79f-4c8c-afaa-9987004b8c69.png)


Your desktop pop-up             |  The figma template
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-21 22-15-42](https://user-images.githubusercontent.com/65233860/197297448-b6312a95-56e3-407b-8ca6-01ce346cd238.png)  |  ![Screenshot from 2022-10-21 22-14-37](https://user-images.githubusercontent.com/65233860/197297457-0554e8e2-a2e1-4018-909e-0a50bc05e6a0.png)

2022-10-22 02:33 UTC, Santiago220991 requested changes
Hi @edahigure, 
I'm Santiago your reviewer for this PR. :wave: :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

 ## Highlights
:heavy_check_mark: No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 02:33 UTC, Santiago220991 commented on style.css
> +  }
As [the last code reviewer suggested](https://github.com/edahigure/Portfolio-setup-and-mobile-first/pull/13#discussion_r1002221758) kindly fix the position and the size of your popup windows on both versions mobile and desktop. :pray: :pray: 
- Please apply the changes in your desktop version and check it with your browser window zoom at 100%. :eyes: :eyes: 
Your design
![image](https://user-images.githubusercontent.com/98363075/197315046-20574107-376d-4d6a-ac0d-576b05be13ab.png)
Figma design
![image](https://user-images.githubusercontent.com/98363075/197315091-ea87a0dc-56b6-47b1-87f3-4676bf2a5e67.png)

- The design in your mobile version is totally different, kindly place the elements in the same way that the Figma template. :+1: :smiley: :smiley: 
Your design.
![image](https://user-images.githubusercontent.com/98363075/197315141-d1e6c740-f9c4-496b-b23d-332b83c98ae6.png)

Figma design
![image](https://user-images.githubusercontent.com/98363075/197315187-3d0cd681-8802-4ee9-a829-ea8e2851c04d.png)

2022-10-22 18:08 UTC, Deepakdanger approved these changes
Hi @edahigure, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Kindly give proper margin & design to the marked place in the picture.
![Screenshot from 2022-10-22 23-33-47](https://user-images.githubusercontent.com/26767383/197356100-b4e95216-ee7d-4cd2-93d7-0a63caada039.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 18:22 UTC, merged